# set base image (host OS)
FROM tensorflow/tensorflow@sha256:c73a8dafeb42
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ffmpeg \
    libsm6 \
    libxext6 \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/*

# set the working directory in the container
WORKDIR /code

# copy the dependencies file to the working directory
COPY requirements.txt .

# install dependencies
RUN pip install -r requirements.txt
RUN pip install pytest
# copy code
COPY src/ /code

ENV PYTHONPATH "${PYTHONPATH}:/code"

# run tests
# Run the tests using unittest
CMD ["python", "-m", "unittest", "discover", "-s", "test", "-p", "*.py"]